language: go
os:
  - linux
  - osx
  - windows
go:
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - 1.9.x
  - 1.8.x
before_install:
  - go get -u github.com/golang/dep/cmd/dep
script:
  - dep ensure
  - go build
