platform:
  - x86
  - x64
environment:
  matrix:
    - GOVERSION: '1.11'
    - GOVERSION: '1.10.4'
    - GOVERSION: '1.9.7'
    - GOVERSION: '1.8.7'
install:
  - cmd: rmdir c:\Go /s /q
  - cmd: appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - cmd: msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - cmd: set Path=c:\Go\bin;c:\gopath\bin;c:\Progra~1\Git\bin
  - cmd: go version
  - cmd: go env
  - cmd: go get -u github.com/golang/dep/cmd/dep
build_script:
  - cmd: cd c:\projects\tinifier-go
  - cmd: dep ensure
  - cmd: go build
